services:
  # servidor
  webserver:
    image: nginx:latest
    container_name: website_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    
 #php
  php:
    image: php8.3:v1
    container_name: website_php
    volumes:
      - ./php/public:/var/www/html/public

#mysql
  db:
    image: mysql:8.0
    container_name: website_mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: app_database
      MYSQL_USER: user_app_database
      MYSQL_PASSWORD: teste1234
    command: --default-authentication-plugin=mysql_native_password
